services:
  redis:
    image: redis:7-alpine
    container_name: understanding-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data   

  mongodb:
    image: mongo:6.0
    container_name: mydb
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data: